// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameData/DataPacks/Entity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DataPacks {

  /// <summary>Holder for reflection information generated from GameData/DataPacks/Entity.proto</summary>
  public static partial class EntityReflection {

    #region Descriptor
    /// <summary>File descriptor for GameData/DataPacks/Entity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9HYW1lRGF0YS9EYXRhUGFja3MvRW50aXR5LnByb3RvEglEYXRhUGFja3Ma",
            "K0dhbWVEYXRhL0RhdGFQYWNrcy9UcmFuc2Zvcm0vUG9zaXRpb24ucHJvdG8a",
            "K0dhbWVEYXRhL0RhdGFQYWNrcy9UcmFuc2Zvcm0vUm90YXRpb24ucHJvdG8a",
            "IUdhbWVEYXRhL0RhdGFQYWNrcy9QcmVmYWJJRC5wcm90byKrAQoGRW50aXR5",
            "EgoKAmlkGAEgASgFEgwKBG5hbWUYAiABKAkSJQoIcHJlZmFiSWQYAyABKAsy",
            "Ey5EYXRhUGFja3MuUHJlZmFiSUQSLwoIcG9zaXRpb24YBCABKAsyHS5EYXRh",
            "UGFja3MuVHJhbnNmb3JtLlBvc2l0aW9uEi8KCHJvdGF0aW9uGAUgASgLMh0u",
            "RGF0YVBhY2tzLlRyYW5zZm9ybS5Sb3RhdGlvbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DataPacks.Transform.PositionReflection.Descriptor, global::DataPacks.Transform.RotationReflection.Descriptor, global::DataPacks.PrefabIDReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DataPacks.Entity), global::DataPacks.Entity.Parser, new[]{ "Id", "Name", "PrefabId", "Position", "Rotation" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Entity : pb::IMessage<Entity> {
    private static readonly pb::MessageParser<Entity> _parser = new pb::MessageParser<Entity>(() => new Entity());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Entity> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataPacks.EntityReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Entity() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Entity(Entity other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      prefabId_ = other.prefabId_ != null ? other.prefabId_.Clone() : null;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      rotation_ = other.rotation_ != null ? other.rotation_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Entity Clone() {
      return new Entity(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prefabId" field.</summary>
    public const int PrefabIdFieldNumber = 3;
    private global::DataPacks.PrefabID prefabId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DataPacks.PrefabID PrefabId {
      get { return prefabId_; }
      set {
        prefabId_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 4;
    private global::DataPacks.Transform.Position position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DataPacks.Transform.Position Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 5;
    private global::DataPacks.Transform.Rotation rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::DataPacks.Transform.Rotation Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Entity);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Entity other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(PrefabId, other.PrefabId)) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Rotation, other.Rotation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (prefabId_ != null) hash ^= PrefabId.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (rotation_ != null) hash ^= Rotation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (prefabId_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PrefabId);
      }
      if (position_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Position);
      }
      if (rotation_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Rotation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (prefabId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PrefabId);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (rotation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rotation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Entity other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.prefabId_ != null) {
        if (prefabId_ == null) {
          PrefabId = new global::DataPacks.PrefabID();
        }
        PrefabId.MergeFrom(other.PrefabId);
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::DataPacks.Transform.Position();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.rotation_ != null) {
        if (rotation_ == null) {
          Rotation = new global::DataPacks.Transform.Rotation();
        }
        Rotation.MergeFrom(other.Rotation);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (prefabId_ == null) {
              PrefabId = new global::DataPacks.PrefabID();
            }
            input.ReadMessage(PrefabId);
            break;
          }
          case 34: {
            if (position_ == null) {
              Position = new global::DataPacks.Transform.Position();
            }
            input.ReadMessage(Position);
            break;
          }
          case 42: {
            if (rotation_ == null) {
              Rotation = new global::DataPacks.Transform.Rotation();
            }
            input.ReadMessage(Rotation);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
